### PR TITLE
Support for building on `x86_64-darwin`

### PR DESCRIPTION
**Pull request by kpadmasola**

### CODE REVIEW

**Comment by luc-tielen** [comment]
BTW: The failing build is due to hlint, which I fixed in another PR, but is not yet merged.

**Comment by kpadmasola** [comment]
Building with these changes on `x86_64-darwin` currently produces the following error:

```bash
$ nix build --print-build-logs
error: output '/nix/store/06xz3q2hvn3m7wh3bn4xfiwyrwrd2ybg-stdenv-darwin' is not allowed to refer to the following paths:
         /nix/store/fzy212s65vik6wlyxv02lmhc22wp0zms-llvm-14.0.1-lib
         /nix/store/v9qbhh73chx2xz2ddjv23plxwbky9wj0-llvm-14.0.1
error: 1 dependencies of derivation '/nix/store/ar3z16dmzcfnj347ds8wgh04dixz2ygm-cabal2nix-2.18.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zy86g8w4mw518kljw2b3kjl2bmr3gbfs-cabal2nix-eclair-lang.drv' failed to build
(use '--show-trace' to show detailed location information)
```

The contents of `/nix/store/zy86g8w4mw518kljw2b3kjl2bmr3gbfs-cabal2nix-eclair-lang.drv` are as follows:
<details><summary>Contents of the derivation</summary>
<p>

```haskell
Derivation
  { outputs =
      fromList
        [ ( "out"
          , DerivationOutput
              { path =
                  "/nix/store/rcrhqlfbx28751izs3ikima7hwr3bydb-cabal2nix-eclair-lang"
              , hashAlgo = ""
              , hash = ""
              }
          )
        ]
  , inputDrvs =
      fromList
        [ ( "/nix/store/0w33zcq6a34pakvqaxyw88b5lpzkvb8s-stdenv-darwin.drv"
          , fromList [ "out" ]
          )
        , ( "/nix/store/ar3z16dmzcfnj347ds8wgh04dixz2ygm-cabal2nix-2.18.0.drv"
          , fromList [ "out" ]
          )
        , ( "/nix/store/n00038lvz7jip14aabwsb3l0lk79yz5z-bash-5.1-p16.drv"
          , fromList [ "out" ]
          )
        ]
  , inputSrcs =
      fromList
        [ "/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh"
        , "/nix/store/vmz9xqv6h3fqpzybcalp1wi9pgrlr7z9-source"
        ]
  , platform = "x86_64-darwin"
  , builder =
      "/nix/store/1kkhc1nyadqkb0c63dpzrsp8pb0bwj3l-bash-5.1-p16/bin/bash"
  , args =
      [ "-e"
      , "/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh"
      ]
  , env =
      fromList
        [ ( "LANG" , "en_US.UTF-8" )
        , ( "LOCALE_ARCHIVE" , "" )
        , ( "__darwinAllowLocalNetworking" , "" )
        , ( "__impureHostDeps"
          , "/bin/sh /usr/lib/libSystem.B.dylib /usr/lib/system/libunc.dylib /dev/zero /dev/random /dev/urandom /bin/sh"
          )
        , ( "__propagatedImpureHostDeps" , "" )
        , ( "__propagatedSandboxProfile" , "" )
        , ( "__sandboxProfile" , "" )
        , ( "allowSubstitutes" , "" )
        , ( "buildCommand"
          , "export HOME=\"$TMP\"\nmkdir -p \"$out\"\ncabal2nix --compiler=ghc-9.0.2 --system=x86_64-apple-darwin --sha256= \"/nix/store/vmz9xqv6h3fqpzybcalp1wi9pgrlr7z9-source\"  > \"$out/default.nix\"\n"
          )
        , ( "buildInputs" , "" )
        , ( "builder"
          , "/nix/store/1kkhc1nyadqkb0c63dpzrsp8pb0bwj3l-bash-5.1-p16/bin/bash"
          )
        , ( "configureFlags" , "" )
        , ( "depsBuildBuild" , "" )
        , ( "depsBuildBuildPropagated" , "" )
        , ( "depsBuildTarget" , "" )
        , ( "depsBuildTargetPropagated" , "" )
        , ( "depsHostHost" , "" )
        , ( "depsHostHostPropagated" , "" )
        , ( "depsTargetTarget" , "" )
        , ( "depsTargetTargetPropagated" , "" )
        , ( "doCheck" , "" )
        , ( "doInstallCheck" , "" )
        , ( "name" , "cabal2nix-eclair-lang" )
        , ( "nativeBuildInputs"
          , "/nix/store/nim0xn498zasgmbjzsgw6y9pichyl02s-cabal2nix-2.18.0"
          )
        , ( "out"
          , "/nix/store/rcrhqlfbx28751izs3ikima7hwr3bydb-cabal2nix-eclair-lang"
          )
        , ( "outputs" , "out" )
        , ( "passAsFile" , "buildCommand" )
        , ( "patches" , "" )
        , ( "preferLocalBuild" , "1" )
        , ( "propagatedBuildInputs" , "" )
        , ( "propagatedNativeBuildInputs" , "" )
        , ( "stdenv"
          , "/nix/store/5xxw3ll3f70y5dywlzv5hrh2xmlzrc2v-stdenv-darwin"
          )
        , ( "strictDeps" , "" )
        , ( "system" , "x86_64-darwin" )
        ]
  }
```

</p>
</details>

**Comment by luc-tielen** [comment]
@kpadmasola You're probably better off closing this PR and adding `"x86_64-darwin"` again to the updated flake.nix. I tried doing it myself, but got permission denied.

**Comment by kpadmasola** [comment]
closing this. will open a new PR for darwin support as suggested by @luc-tielen

**Pull request closed without merging**
